matrix:
  fast_finish: true

image:
  - Visual Studio 2017

platform: x64

SLBuildDirectory: streamlabs-build
SLGenerator: Visual Studio 15 2017 Win64
SLDistributeDirectory: distribute
SLFullDistributePath: $(SLBuildDirectory)\$(SLDistributeDirectory)
SLArch: x64
SignTool: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe
StreamlabsPfxSecret:
  secure: iZlMSWnmH5FQDpa+/0SgXIyvCobkElj2y5lu94Uo8VnTWHTeTC1/bpVkzsLreENocomvDB5ywsa3+QdathRp8A==
StreamlabsSecret:
  secure: hr+VpykbGiCI5I0ltiqH667wh/YQx2Fi5SBLfkOWHSg=


install:
  - git submodule update --init --recursive

build_script:
  - cmd: ci\cmake-build.cmd
