matrix:
  fast_finish: true

image:
  - Visual Studio 2017

platform: x64

environment:
  DistributeDirectory: distribute

clone_folder: c:\projects\source

install:
  - git submodule update --init --recursive

build_script:
- cmd: mkdir build
- cmd: cd build
- cmd: cmake c:\projects\source -G "Visual Studio 15 Win64"
- cmd: cmake --build . --config "RelWithDebugInfo"

after_build:
- copy "RelWithDebugInfo\data\*" DistributeDirectory\data\
- copy "RelWithDebugInfo\obs-plugins\*" DistributeDirectory\obs-plugins\

