image:
  - Visual Studio 2017

clone_folder: c:\projects\source


install:
  - git submodule update --init --recursive

build_script:
- cmd: mkdir build
- cmd: cd build
- cmd: cmake c:\projects\source -G "Visual Studio 15"
- cmd: cmake --build . --config "Debug"

