matrix:
  fast_finish: true

image:
  - Visual Studio 2017

platform: x64

environment:
  SignTool: C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe
  StreamlabsPfxSecret:
    secure: iZlMSWnmH5FQDpa+/0SgXIyvCobkElj2y5lu94Uo8VnTWHTeTC1/bpVkzsLreENocomvDB5ywsa3+QdathRp8A==
  StreamlabsSecret:
    secure: hr+VpykbGiCI5I0ltiqH667wh/YQx2Fi5SBLfkOWHSg=
  AWSId:
    secure: mCkabszlS+XuJkjmIFM4t6Hom4jvUfNqbxlmQXKPJNE=
  AWSSecretKey:
    secure: dGl7YDpzqXV+ucEwwo6QEiTjQBSThcakfE70aKWrgjUeLy3jFJsjgbnnGPeUIU+k
  LibobsFile: libobs-debug-22.0.3-sl.301-win32-x64.7z

clone_folder: c:\projects\source

install:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - ps: Read-S3Object -AccessKey $env:AWSId -SecretKey $env:AWSSecretKey -BucketName faces-internal.streamlabs.com -Key $env:LibobsFile -File $env:LibobsFile -Region us-west-2
  - 7z x "%LibobsFile%" -oc:\projects\source\build\ -r
  - ps: $env:SignedArtifact = "facemask-plugin-$(git describe --tags --abbrev=0)"
  - ps: $env:UnsignedArtifact = "facemask-plugin-$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - ps: $env:FM_PLUGIN_APPVEYOR_BUILD=1
  - cmd: cmake c:\projects\source -G "Visual Studio 15 Win64"
  - cmd: cmake --build . --config RelWithDebInfo

after_build:
- cmd: tar cvaf "%UnsignedArtifact%.tar.gz" "distribute/slobs/RelWithDebInfo" 

before_deploy:
- echo %CD%
- nuget install secure-file -ExcludeVersion
- ps: c:\projects\source\ci\win-signed-build.ps1
- tar cvaf "%SignedArtifact%.tar.gz" "distribute"
- ps: Push-AppveyorArtifact "$env:SignedArtifact.tar.gz"

deploy:
  - provider: S3
    access_key_id:
      secure: mCkabszlS+XuJkjmIFM4t6Hom4jvUfNqbxlmQXKPJNE=
    secret_access_key:
      secure: dGl7YDpzqXV+ucEwwo6QEiTjQBSThcakfE70aKWrgjUeLy3jFJsjgbnnGPeUIU+k
    bucket: faces-internal.streamlabs.com
    folder: facemask-plugin-deployment
    region: us-west-2
    set_public: true
    artifact: $(SignedArtifact).tar.gz
    on:
      appveyor_repo_tag: true

artifacts:
  - path: $(UnsignedArtifact).tar.gz
    name: Unsigned Artifact